apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-gateway-options
  namespace: openshift-ingress
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: "1"
                memory: 256Mi
              limits:
                cpu: "2"
                memory: 2Gi
  horizontalPodAutoscaler: |
    spec:
      minReplicas: 1
      maxReplicas: 2
