apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lsd-genai-playground
  namespace: a-project
  annotations:
    openshift.io/display-name: lsd-genai-playground
  labels:
    opendatahub.io/dashboard: "true"
spec:
  replicas: 1
  network:
    allowedFrom:
      namespaces:
        - a-project
    exposeRoute: false
  server:
    distribution:
      name: rh-dev
    userConfig:
      configMapName: llama-stack-config
    containerSpec:
      name: llama-stack
      port: 8321
      command:
        - /bin/sh
        - -c
        - llama stack run /etc/llama-stack/config.yaml
      env:
        - name: VLLM_TLS_VERIFY
          value: "false"
        - name: MILVUS_DB_PATH
          value: ~/.llama/milvus.db
        - name: FMS_ORCHESTRATOR_URL
          value: http://localhost
        - name: VLLM_MAX_TOKENS
          value: "2048"
        - name: VLLM_API_TOKEN_1
          value: fake
        - name: VLLM_API_TOKEN_2
          value: fake
        - name: LLAMA_STACK_CONFIG_DIR
          value: /opt/app-root/src/.llama/distributions/rh/
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: "2"
          memory: 12Gi
